### ISSUE TITLE
no output what so ever

### ISSUE THREAD

**Issue by t2kx** [Azure/azqr#94] opened 2023-06-26 05:57 UTC
## Expected Behavior

I expect some output when running the azqr scan command

## Actual Behavior

azqr scan
2023/06/26 07:51:51 Generating Report: azqr_report_2023_06_26_T075150.xlsx
2023/06/26 07:51:51 Skipping Overview. No data to render
2023/06/26 07:51:52 Skipping Recommendations. No data to render
2023/06/26 07:51:52 Skipping Services. No data to render
2023/06/26 07:51:52 Skipping Defender. No data to render
2023/06/26 07:51:52 Skipping Advisor. No data to render
2023/06/26 07:51:52 Skipping Costs. No data to render
2023/06/26 07:51:52 Scan completed.

## Steps to Reproduce the Problem
az login successful , account set also , full access to subscription , still no output ...

**Comment by cmendible** [comment] 2023-06-26 13:25
HI @t2kx,

Some questions:

* what version are you running? Run `azqr --version` if not sure.
* do you only have virtual machines deployed?
*

**Comment by cmendible** [comment] 2023-07-04 19:20
can you please run th efollowing: 

``` powershell
$env:AZURE_SDK_GO_LOGGING="all"
azqr scan > azqr_results.txt
```

and share the `azqr_results.txt` file with me?

**Comment by cmendible** [comment] 2023-09-06 19:46
Closing since issue has not been reproduced and no feedback provided.

**Closed by cmendible** 2023-09-06 19:46 UTC
